### ISSUE TITLE
Taux CFE eg. Anglefort

### ISSUE THREAD

**Issue by cactuschibre** [noraj/BB-legal-FR#2]
Bonjour,

Je ne comprends pas la référence à Anglefort (section [Draft] CFE).

"_Le CFE de Paris est 16,52% =>, mais il y a un paquet de ville avec des taux aux alentours de 7%. Eg à ANGLEFORT (01350) le taux est de 4% en 2018._"

Via https://www.collectivites-locales.gouv.fr/fiscalite-locale-communes-0, le taux affiché en 2019 et 2018 est de 20,64%.

Je regarde au mauvais endroit (je suis conscient que c'est un draft mais cela m'interpelle) ?

Sinon, super initiative !

**Comment by noraj** [comment]
Salut,
Le lien que tu donnes a pas les bonnes données, tu te rends compte qu'il en manque beaucoup et qu'il n'y a pas les 30 000+ villes.
Les données complètes sont trouvable ici: https://www.data.gouv.fr/fr/datasets/impots-locaux/, il y a un zip avec un tableau ultra complet pour chaque département.

**Comment by noraj** [comment]
PS : pour discuter https://github.com/noraj/BB-legal-FR/discussions
