### ISSUE TITLE
Clarification TVA

### ISSUE THREAD

**Issue by theflofly** [noraj/BB-legal-FR#6]
Concernant cette phrase:

"Au-delà d’un certain niveau de revenu tiré de son activité sur la plateforme ou de plusieurs plateformes, le Hunter pourra être assujetti à la TVA et en conséquence devra facturer, collecter et reverser à l’administration fiscale la TVA afférente à chaque opération."

Si un bug est payé 1000 euros par une plateforme française, est-ce que la plateforme donne en fait 1200 euros pour tenir compte de la TVA si le hunter y est assujetti ?

Ou alors le hunter doit t'il prendre 20% sur le bug et le donner à l'état en tant que TVA?

**Comment by noraj** [comment]
La non collecte de TVA c'est plutôt quand tu génères des factures toi même. Les plateformes connaissent pas tes revenus et si tu a déjà dépassé le seuil ou non, donc quand elles génèrent les factures automatiquement pour toi il y a des chances que ce soit déjà payé en TTC et que oui tu doive reverser 20%.
Attention à ton profil sur les plateformes multi-nationales, quand tu rempli le formulaire fiscale il peut y en avoir un pour les particuliers (pas concernés en France) et un pour les entreprises (pour nous vu qu'on est une EI), il faudra donc remplir le bon formulaire pour que la TVA soit prise en compte.
